---
- name: Make directory contain Vagrantfile
  file:
    path: /tmp/{{ vm_name }}
    state: directory

- name: Upload Vagrantfile
  copy:
    src: ./Vagrantfile.j2
    dest: /tmp/{{ vm_name }}

- name: Create VM 
  shell: |
    cd /tmp/{{ vm_name }}
    vagrant up