---
### This playbook use to remove mcf

# - name: Get ISec and MFE Packages   
# TODO: get list package 

- name: Remove package
  yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - MFEcma 
      - MFErt
      - ISecESP
      - ISecESPFileAccess
      - ISecRt
      - ISecTP