---
# This playbook contains env plays that will be run on all nodes.

- name: Create the repository for HN-repo
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'HN-local.repo', dest: '/etc/yum.repos.d/HN-local.repo' }
    - { src: 'HN-nodejs.repo', dest: '/etc/yum.repos.d/HN-nodejs.repo' }

