---
# This playbook will install Nginx

- name: Add epel-release repository
  yum:
    name: epel-release
    state: present

- name: Install Nginx 
  yum:
    name: nginx
    state: present

#- name: Insert Index Page
#    template:
#      src: index.html
#      dest: /usr/share/nginx/html/index.html

#- name: Copy nginx configuration
#  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: Start Nginx
  service: name=nginx state=started enabled=yes
